### ISSUE TITLE
No video found

### ISSUE THREAD

**Issue by miguelogin** [vidify/vidify#106]
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
The video wasn't found, either because of an issue with your internet connection or because the provided data was invalid. For more information, enable the debug mode.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
The video wasn't found, either because of an issue with your internet connection or because the provided data was invalid. For more information, enable the debug mode.

**Comment by marioortizmanero** [comment]
Is this a regular issue, or a one-time thing? You most likely just have to update youtube-dl, as the error says.

**Comment by miguelogin** [comment]
It's regular. Happens on every music I play, even famous musics. Where should I type the command to update?

**Comment by marioortizmanero** [comment]
I haven't implemented automatic youtube-dl updating inside Vidify yet, so you'll have to open a new terminal and type `youtube-dl -U`.

**Comment by miguelogin** [comment]
Nevermind. I updated the youtube-dl:
`Requirement already up-to-date: youtube-dl in c:\users\migue\appdata\local\programs\python\python38-32\lib\site-packages (2020.6.16.1)`

Still got the same issue message.

**Comment by miguelogin** [comment]
Thanks. Found a way to update youtube-dl and it's working now. 😄

**Comment by marioortizmanero** [comment]
Great! If you find any other issues please let me know :)
