### ISSUE TITLE
2.2.0 not remebering configuration

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [vidify/vidify#75]
Hi,

I just updated to the new version, and I noticed that vidify is no longer remembering configuration like it was before. It shows me the selection screen every time ( the new selection screen looks very nice btw :smile: )

This is my config file:
```
andrew@andrew-gentoo-pc ~ % cat .config/vidify/config.ini
[Defaults]
api = MPRIS_LINUX
player = VLC
audiosync = true
```

and this is the output of `vidify --debug`
```
andrew@andrew-gentoo-pc ~ % vidify --debug
[22:07:06.114] INFO: Loading setup screen
[22:07:06.145] INFO: Created API card: MPRIS_LINUX (enabled=True, selected=True)
[22:07:06.146] INFO: Created API card: SWSPOTIFY (enabled=False, selected=False)
[22:07:06.147] INFO: Created API card: SPOTIFY_WEB (enabled=True, selected=False)
[22:07:06.148] INFO: Added Player card: VLC (selected=True)
[22:07:06.149] INFO: Added Player card: MPV (selected=False)
[22:07:06.149] INFO: Added Player card: EXTERNAL (selected=False)
<-- this is when I press the continue button -->
[22:11:41.432] INFO: Selected: api=MPRIS_LINUX, player=VLC
[22:11:41.466] INFO: Using MPRIS_LINUX as the API
[22:11:41.485] INFO: Using VLC as the player
[22:11:42.520] INFO: Looking for players
[22:11:42.525] INFO: Skipping org.mpris.MediaPlayer2.spotify because it's not playing at the moment
[22:11:42.525] INFO: Connection attempts left: 299
[22:11:43.566] INFO: Looking for players
[22:11:43.569] INFO: Skipping org.mpris.MediaPlayer2.spotify because it's not playing at the moment
[22:11:43.569] INFO: Connection attempts left: 298
[22:11:44.617] INFO: Looking for players
[22:11:44.621] INFO: Using org.mpris.MediaPlayer2.spotify
[22:11:44.622] INFO: Succesfully connected to the API
```

Also, the output of the audiosync module seems to be output to the console now even if the `--debug` flag is not set. Whereas previously this output was not shown in the console unless the `--debug` flag was set.

**Comment by marioortizmanero** [comment]
I'm glad you liked the new screen! The issue you're reporting is intended. Vidify does remember the config; the player and api will be already selected, and all you have to do is click the "Continue" button. After the re-design I decided to leave it that way to get rid of the `--player None` hack, and so that it's easier to switch between APIs and Players without having to use the command line at all.

Initially, the skip was a temporal solution until the [menu was finished](https://github.com/vidify/vidify/issues/19). But it's going to take longer than I thought because it's a pain to program it.


There's an issue about the debug messages open that I need to work on: https://github.com/vidify/audiosync/issues/51.

**Comment by AndrewAmmerlaan** [comment]
> I'm glad you liked the new screen! The issue you're reporting is intended. Vidify does remember the config; the player and api will be already selected, and all you have to do is click the "Continue" button. After the re-design I decided to leave it that way to get rid of the --player None hack, and so that it's easier to switch between APIs and Players without having to use the command line at all.

Ooh I see, I hadn't noticed yet that the config options were preselected. This does indeed make it easier to switch back and forth between players/api's. However, personally I liked how before it was start-and-go (no clicks required). But maybe that is something that can come back with the Qt quick menu in the future. In the meantime though, could we maybe have the 'enter' key continue as well? That way when vidify is started it is enough to just hit the enter key to continue with the default options as set in the config file. At the moment I can move focus with tab/shift+tab as expected, but moving focus to the 'continue' button and pressing the enter key doesn't actually continue. I think this could be done by setting the `.setFocus()` attribute on the 'continue' button and then using the `.Qt.Key_Return` event to actually press the button. (idk why PyQt doesn't do 'enterkey-presses-focussed-key' by default, shouldn't it do that by default? )

**Comment by marioortizmanero** [comment]
That's a neat idea, just made a commit implementing it. You have to use the spacebar, not the enter key. The thing is that this feature is a bit obscure, but it was fairly easy to implement so I'll leave it like that.

**Comment by AndrewAmmerlaan** [comment]
> That's a neat idea, just made a commit implementing it. You have to use the spacebar, not the enter key.

Awesome, thanks, that will save me a couple of clicks xD
